<?= $this->part('admin', 'index', 'navigation', array('active' => 'linksedit')); ?>

<div id="admCont">
    <?= $this->part('admin', 'index', 'header', array('userInfo' => $this->userInfo, 'title' => 'Link Management - Edit Link')); ?>
    <?= $this->part('admin', 'index', 'messages', array(
        'successes' => $this->successes,
        'errors'     => $this->errors,
        'warnings'     => $this->warnings,
        'infos'     => $this->infos
    )); ?>

    <div id="mainContent">
        <form method="post" action="<?= $this->route('admin', 'links', 'edit', array('id' => $this->link->linkId)); ?>">
            <table class="dataTableEdit">
                <tr>
                    <td>Link ID : </td>
                    <td id="linkId"><?= $this->link->linkId; ?></td>
                </tr>
                <tr>
                    <td>Title : </td>
                    <td><input type="text" name="linkTitle" id="linkTitle" value="<?= $this->link->title; ?>" /></td>
                </tr>
                <tr>
                    <td>Link : </td>
                    <td><input type="text" name="linkLink" id="linkLink" value="<?= $this->link->link; ?>" /></td>
                </tr>
                <tr>
                    <td>Description : </td>
                    <td><textarea name="description" id="description"><?= $this->link->description; ?></textarea></td>
                </tr>
                <tr>
                    <td>Creation Date : </td>
                    <td><input type="text" name="creationDate" id="creationDate" value="<?= $this->link->creationDate; ?>" /></td>
                </tr>
                <tr>
                    <td>Updated Date : </td>
                    <td><?= $this->link->updatedDate; ?></td>
                </tr>
                <tr>
                    <td>Featured : </td>
                    <td><input type="checkbox" name="featured" id="featured" <?= ($this->link->featured == 1 ? 'checked="checked"' : ''); ?> /></td>
                </tr>
                <tr>
                    <td>Deleted : </td>
                    <td><input type="checkbox" name="deleted" id="deleted" <?= ($this->link->deleted == 1 ? 'checked="checked"' : ''); ?> /></td>
                </tr>
                <tr>
                    <td></td>
                    <td><input type="submit" value="Update Link" /></td>
                </tr>
            </table>
        </form>
    </div>

</div>