<header>
    <div class="row-fluid">
        <div class="span6">
            <h2><?= $this->title; ?></h2>
        </div>
        <div class="span6" id="userLinks">
            <?= date('D, dS F Y') . ' &nbsp; :: &nbsp; ' . date('h:i:s A'); ?> &nbsp; :: &nbsp;
            <a href="<?= $this->route('admin', 'index', 'logout'); ?>">
                Logout [<?= $this->userInfo->firstname . ' ' . $this->userInfo->lastname; ?>]
            </a>
        </div>
    </div>
</header>