<div id="main-content-header">
    <div class="row-fluid">
        <div class="span2">
            <div class="pic"><img src="/img/slogan/anujnaircloseup.png" alt="Anuj Nair close up picture" /></div>
        </div>
        <div class="span10">
            <h2>About Anuj Nair</h2>
            <div class="subh2">
                 Although a Maths Graduate from the University of Nottingham, Anuj Nair has always had a strong passion for
                 creating innovative websites with attractive interfaces and a smooth user experience in mind. You can read
                 more about how he progressed to become a web developer below.
            </div>
        </div>
    </div>
</div>

<div id="main-content-body">
    <div class="row-fluid">
        <div class="span12">
            <section class="main-content-body-left">
                <h3>&quot;Hello World&quot; - Not My First Website</h3>
                <article>
                    <p><?= date('Y') - 2002; ?> years ago, I entered the programming world with much enthusiasm and a thirst to
                    be able to build my own applications and websites. I took my first few small steps by creating simple pascal
                    scripts in a Delphi/Pascal hybrid IDE which were designed to control your mouse and keyboard to complete
                    repetative tasks automatically.</p>

                    <p>These scripts grew to the point where they were unmanagable without automating some of the commerical tasks
                    associated with distributing them, and so I decided to jump into the deep end of web development and create a
                    basic ecommerce site. This site allowed me to sell my programs easily, distribute updates automatically, and
                    quickly became a powerful way to deliver news and other vital information to my customers.</p>

                    <p>That was my first insight in seeing just how powerful web development actually was; My passion for web
                    development was born.</p>
                </article>
                <h3>How My Passion For Web Development Has Grown</h3>
                <article>
                    <p>Besides the usual development of other websites through freelancing, it is the design, creation and implementation
                    of dynamic web <em>applications</em> which has always interested me - The constant creation of new information
                    from user generated content, or solving security and scalability issues are tasks which I love tackling and find
                    very satisfying to solve. A few projects I have tackled include:</p>
                    <ul>
                        <li><strong>Advanced Authentication Systems</strong> - Authenticating a user on multiple levels for desktop
                        applications by making API calls to my web server. These include:</li>
                        <ul>
                            <li>Secure authentication between the client and server</li>
                            <li>Handling shared keys and shared accounts via whitelisting and blacklisting</li>
                            <li>Different levels of authentication</li>
                            <li>Accounting for security, performance and scalability</li>
                        </ul>
                    </ul>
                    <ul>
                        <li><strong>Content Management Systems</strong> integrating with 3<sup>rd</sup> party scripts, such as those
                        from phpBB2 and phpBB3 forums to centralize forum actions. These applications include:</li>
                        <ul>
                            <li>Full admin panels to manage all of the dynamic and customizable sections of the sites</li>
                            <li>User management and user permission levels</li>
                            <li>Solving for large amounts of traffic and engagement</li>
                            <li>Filtering and validating user submitted data to avoid XSS</li>
                        </ul>
                    </ul>
                    <ul>
                        <li><strong>Parsers &amp; Scrapers</strong> for IMDB and iTunes to manipulate data into language readable formats
                        (JSON, XML etc.)</li>
                    </ul>
                    <ul>
                        <li><strong>Mobile Optimisation</strong> through the use of responsive layouts</li>
                    </ul>
                    <ul>
                        <li><strong>Data Mining &amp; Data Analysis</strong> to summarize and idenfity trends from large amounts
                        of data.</li>
                    </ul>
                </article>
                <h3>Where I Am Now</h3>
                <article>
                    <p>Currently I work for a technology and marketting company, where I lead a product development team.</p>

                    <p>During my time in this role, my responsibilities have ranged from internationalization and site development 
                    to integrating 3<sup>rd</sup> party partners; data tracking and analysis to large scale product development, all 
                    whilst being complient with PCI security standards and EU data privacy.</p>
                    
                    <p>If you'd like to learn more about me or what I do, please <a href="<?= $this->route('default', 'contact', 'index'); ?>">contact me</a>.</p>
                </article>
            </section>
        </div>
    </div>
</div>