<?php echo $this->doctype(); ?>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<?php echo $this->headMeta(); ?>

<?php echo $this->headLink(); ?>

<?php echo $this->headScript(); ?>

<?php echo $this->headTitle(); ?>

<?php echo $this->headStyle() ?>

</head>

<body>
    <div id="container">
        <?php echo $this->layout()->content; ?>
    </div>

    <?php echo $this->layout()->queryDump; ?>

</body>

</html>