<?= $this->doctype(); ?>

<html lang="en">

<head>
<?= $this->headMeta(); ?>

<?= $this->headLink(); ?>

<?= $this->headTitle(); ?>

<?= $this->headStyle() ?>

</head>

<body>
    <div id="container">
        <header>
            <div class="inner">
                <div id="logo" class="pull-left">
                    <a href="/"><img src="/img/logo.png" alt="Anuj Nair - Website Designer and Developer" /></a>
                </div>
                <nav>
                    <ul class="buttons">
                        <li id="nav-home">
                            <a class="button" href="/">
                                <span class="icon-home icon-white"></span> Home
                            </a>
                        </li>
                        <li id="nav-portfolio">
                            <a class="button" href="<?= $this->route("default", "portfolio", "index"); ?>">
                                <span class="icon-briefcase icon-white"></span> Portfolio
                            </a>
                        </li>
                        <li id="nav-blog">
                            <a class="button" href="<?= $this->route("default", "blog", "index"); ?>">
                                <span class="icon-comment icon-white"></span> Blog
                            </a>
                        </li>
                        <li id="nav-about">
                            <a class="button" href="<?= $this->route("default", "about", "index"); ?>">
                                <span class="icon-user icon-white"></span> About
                            </a>
                        </li>
                        <li id="nav-links">
                            <a class="button" href="<?= $this->route("default", "links", "index"); ?>">
                                <span class="icon-globe icon-white"></span> Links
                            </a>
                        </li>
                        <li id="nav-contact">
                            <a class="button" href="<?= $this->route("default", "contact", "index"); ?>">
                                <span class="icon-envelope icon-white"></span> Contact
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </header>
        <div class="inner" id="main-content">
            <?= $this->layout()->content; ?>

        </div>
        <div id="push"></div>
    </div>
    <footer>
        <div class="inner">
            <div class="pull-left" id="footer-copy">
                Copyright &copy; 2009-<?= date('Y'); ?> <a href="/">Anuj Nair</a>
            </div>
            <div class="pull-right" id="footer-rights">
                Valid <a href="http://jigsaw.w3.org/css-validator/check/referer?profile=css3">CSS</a> &nbsp; | &nbsp;
                Valid <a href="http://validator.w3.org/check?uri=referer">HTML</a> &nbsp; | &nbsp;
                All Rights Reserved
            </div>
        </div>
    </footer>

    <?= $this->headScript(); ?>

</body>

</html>