<?= $this->part('admin', 'index', 'navigation', array('active' => 'blogedit')); ?>

<div id="admCont">
    <?= $this->part('admin', 'index', 'header', array('userInfo' => $this->userInfo, 'title' => 'Blog Management - Edit Blog Entry ' . $this->blog->blogId)); ?>
    <?= $this->part('admin', 'index', 'messages', array(
        'successes' => $this->successes,
        'errors'     => $this->errors,
        'warnings'     => $this->warnings,
        'infos'     => $this->infos
    )); ?>

    <div id="mainContent">

        <form method="post" action="<?= $this->route('admin', 'blog', 'edit', array('id' => $this->blog->blogId)); ?>">
            <table class="dataTableEdit" id="editBlog">
                <tr>
                    <td>Blog ID : </td>
                    <td id="blogId"><?= $this->blog->blogId; ?></td>
                </tr>
                <tr>
                    <td>Title : </td>
                    <td><input type="text" name="blogTitle" id="blogTitle" value="<?= $this->blog->title; ?>" /></td>
                </tr>
                <tr>
                    <td>Sub Title : </td>
                    <td><textarea name="blogSubTitle" id="blogSubTitle"><?= $this->blog->subtitle; ?></textarea></td>
                </tr>
                <tr>
                    <td>Main Contents : </td>
                    <td><textarea name="contents" id="contents"><?= $this->blog->contents; ?></textarea></td>
                </tr>
                <tr>
                    <td>BBCode : </td>
                    <td id="bbcode-container">
                        <span class="bbcode-title">Bold</span>[b][/b]<br />
                        <span class="bbcode-title">Italics</span>[i][/i]<br />
                        <span class="bbcode-title">Sub Header</span>[subheader][/subheader]<br />
                        <span class="bbcode-title">Link</span>[url="link"]name[/url]<br />
                        <span class="bbcode-title">Image</span>[img]link[/img]<br />
                        <span class="bbcode-title">List</span>[list][/list]<br />
                        <span class="bbcode-title">Bullet</span>[*]<br />
                        <span class="bbcode-title">Inline Code</span>[code mode="inline" lang="lang"]code[/code]<br />
                        <span class="bbcode-title">Full Code</span>[code mode="full" lang="lang"]code[/code]<br />
                    </td>
                </tr>
                <tr>
                    <td>Creation Date : </td>
                    <td><input type="text" name="creationDate" id="creationDate" value="<?= $this->blog->creationDate; ?>" /></td>
                </tr>
                <tr>
                    <td>Updated Date : </td>
                    <td><?= $this->blog->updatedDate; ?></td>
                </tr>
                <tr>
                    <td>Disable Comments : </td>
                    <td><input type="checkbox" name="disableComments" id="disableComments" <?= ($this->blog->isCommentDisabled == 1 ? 'checked="checked"' : ''); ?> /></td>
                </tr>
                <tr>
                    <td>Deleted : </td>
                    <td><input type="checkbox" name="deleted" id="deleted" <?= ($this->blog->deleted == 1 ? 'checked="checked"' : ''); ?> /></td>
                </tr>
                <tr>
                    <td></td>
                    <td><input type="submit" value="Update Blog" /></td>
                </tr>
            </table>
        </form>

        <table class="dataTableEdit" id="blogTags">
            <tr>
                <td>Assigned Tags:</td>
                <td id="assignedTags">
                    <?php foreach($this->blog->tags as $t) { ?>
                        <div id="tag<?= $t->tagId; ?>" class="existingTag assignedTag">
                            <?= $t->tagName; ?>
                            <a href="#"><img src="/img/icons/bullet_delete.png" /></a>
                        </div>
                    <?php } ?>
                </td>
            </tr>
            <tr>
                <td>Available Tags:</td>
                <td id="availableTags">
                    <?php foreach($this->unusedTags as $u) { ?>
                        <div id="tag<?= $u->tagId; ?>" class="existingTag availableTag">
                            <?= $u->tagName; ?>
                            <a href="#"><img src="/img/icons/bullet_add.png" /></a>
                        </div>
                    <?php } ?>
                </td>
            </tr>
            <tr>
                <td>Add New Tag:</td>
                <td>
                    <form method="post" action="<?= $this->route('admin', 'blog', 'addtag', array('id' => $this->blog->blogId)); ?>">
                        <input type="text" name="newTagText" id="newTagText" value="" />
                        <input type="submit" value="Create Tag" />
                    </form>
                </td>
            </tr>
            <tr>
                <td>Delete Tag:</td>
                <td>
                    <form method="post" action="<?= $this->route('admin', 'blog', 'removetag', array('id' => $this->blog->blogId)); ?>">
                        <select name="removeTagId" id="removeTagId">
                            <option value="0">-- Please Select --</option>
                            <?php foreach($this->allTags as $t) { ?>
                                <option value="<?= $t->tagId; ?>"><?= $t->tagName; ?></option>
                            <?php } ?>
                        </select>
                        <input type="submit" value="Remove Tag" />
                    </form>
                </td>
            </tr>
            <tr>
                <td colspan="2" class="center" id="tagError"></td>
            </tr>
        </table>

    </div>

</div>