<article class="main-content-body-left">
    <h3>
        <a href="<?= $this->url(array(
                'id' => $this->site->siteId,
                'name' => $this->urltitle($this->site->siteName)
            ),
            'site',
            true
        ); ?>">
            <?= $this->site->siteName; ?>
        </a>
    </h3>
    <div class="row-fluid row-portfolio">
        <div class="span6 row-portfolio-image">
            <a href="<?= $this->url(array(
                    'id'   => $this->site->siteId,
                    'name' => $this->urltitle($this->site->siteName)
                ),
                'site',
                true
            ); ?>">
                <img src="/img/portfolio/<?= $this->site->image; ?>" alt="<?= $this->site->siteName; ?> Portfolio Image"/>
            </a>
        </div>
        <div class="span6 row-portfolio-text">
            <?= $this->site->abstract; ?>
        </div>
    </div>
    <div class="row-fluid row-portfolio row-portfolio-border">
        <div class="pull-right">
            <a class="button morebutton" href="<?= $this->url(array(
                    'id'   => $this->site->siteId,
                    'name' => $this->urltitle($this->site->siteName)
                ),
                'site',
                true
            ); ?>">
                <span class="icon-white icon-arrow-right"></span>
                More Info
            </a>
        </div>
        <? if (count($this->site->tags) > 0) { ?>
            <div class="row-portfolio-tags">
                    <? foreach ($this->site->tags as $tag) { ?>
                        <a href="<?= $this->url(array(
                                'id' => $tag->tagId,
                                'name' => $this->urltitle($tag->tagName)
                            ),
                            'blogTags',
                            true
                        ); ?>">
                            <?= $tag->tagName; ?>
                        </a>
                    <? } ?>
            </div>
        <? } ?>
    </div>
</article>